name: Build and Deploy

on:
  workflow_run:
    workflows: ['Run Tests']
    branches: [main]
    types:
      - completed

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Build project
        run: yarn build

      - name: Remove dev-dependencies
        run: yarn install --frozen-lockfile --production

      - name: Move node_modules to dist folder
        run: mv ./node_modules ./dist

      - name: Show size project
        run: du -hs ./dist

      - name: Stop PM2 Application
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DIGITAL_OCEAN_IP }}
          username: ${{ secrets.DIGITAL_OCEAN_USER }}
          key: ${{ secrets.DIGITAL_OCEAN_SSH }}
          script: pm2 stop ${{ secrets.DIGITAL_OCEAN_PM2_APPNAME }}

      - name: copy file via ssh key
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.DIGITAL_OCEAN_IP }}
          username: ${{ secrets.DIGITAL_OCEAN_USER }}
          key: ${{ secrets.DIGITAL_OCEAN_SSH }}
          source: 'dist'
          target: ${{ secrets.DIGITAL_OCEAN_APP_PATH }}
          strip_components: 1

      - name: Start PM2 Application
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DIGITAL_OCEAN_IP }}
          username: ${{ secrets.DIGITAL_OCEAN_USER }}
          key: ${{ secrets.DIGITAL_OCEAN_SSH }}
          script: pm2 start ${{ secrets.DIGITAL_OCEAN_PM2_APPNAME }}
