name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  run_unit_tests:
    runs-on: ubuntu-latest
    steps:
      # Get code
      - uses: actions/checkout@v2
        
      # Setup node version with 12.x
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      
      # Setup for caching node_modules
      - uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      # Environment contains yarn and npm by default
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      
      # Run jest tests
      - name: Run Unit Tests
        run: yarn test --verbose --runInBand --bail
        
  run_e2e_tests:
    runs-on: ubuntu-latest
    steps:
      # Get code
      - uses: actions/checkout@v2
        
      # Setup node version with 12.x
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      
      # Setup for caching node_modules
      - uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      # Environment contains yarn and npm by default
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      
      - name: Run E2E Tests
        run: yarn test:e2e --verbose --runInBand --bail
    
  build_and_deploy:
    runs-on: ubuntu-latest
    needs: [run_unit_tests, run_e2e_tests]

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Build project
        run: yarn build

      - name: Remove dev-dependencies
        run: yarn install --frozen-lockfile --production
      
      - name: Move node_modules to dist folder
        run: mv ./node_modules ./dist

      - name: Show size project
        run: du -hs ./dist
        
      - name: Stop PM2 Application
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DIGITAL_OCEAN_IP }}
          username: ${{ secrets.DIGITAL_OCEAN_USER }}
          key: ${{ secrets.DIGITAL_OCEAN_SSH }}
          script: pm2 stop ${{ secrets.DIGITAL_OCEAN_PM2_APPNAME }}
      
      - name: copy file via ssh key
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.DIGITAL_OCEAN_IP }}
          username: ${{ secrets.DIGITAL_OCEAN_USER }}
          key: ${{ secrets.DIGITAL_OCEAN_SSH }}
          source: "dist/**/*.*"
          target: ${{ secrets.DIGITAL_OCEAN_APP_PATH }}

      - name: Stop PM2 Application
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DIGITAL_OCEAN_IP }}
          username: ${{ secrets.DIGITAL_OCEAN_USER }}
          key: ${{ secrets.DIGITAL_OCEAN_SSH }}
          script: pm2 start ${{ secrets.DIGITAL_OCEAN_PM2_APPNAME }}